// <auto-generated />
namespace GAP.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class GAPShoesInitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GAPShoesInitial));
        
        string IMigrationMetadata.Id
        {
            get { return "201710032330369_GAPShoesInitial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
